/**
 * @module OrderRepository
 * @description Data-access layer for the `orders` table.
 *
 * All read methods use `this.query()` from `BaseRepository` which
 * automatically filters out soft-deleted rows.
 * Write methods (`create`, `updateStatus`) accept an optional transaction
 * client so they can participate in the `CreateOrderUseCase` transaction.
 *
 * @see shared/BaseRepository.ts
 * @see modules/orders/IOrderRepository.ts
 */
import "reflect-metadata";
import { inject, singleton } from "tsyringe";
import { Knex } from "knex";
import { DATABASE_PROVIDER, DatabaseProvider } from "db/DatabaseProvider.js";
import { BaseRepository } from "shared/BaseRepository.js";
import { IOrderRepository } from "./IOrderRepository.js";
import { Order, OrderStatus } from "./types.js";

/**
 * Concrete repository for the `orders` table.
 *
 * @remarks
 * Decorated with `@singleton()` so the DI container creates exactly one
 * instance and all injections share the same Knex connection pool reference.
 */
@singleton()
export class OrderRepository
    extends BaseRepository<Order>
    implements IOrderRepository
{
    protected readonly table = "orders";

    constructor(
        @inject(DATABASE_PROVIDER)
        private readonly dbProvider: DatabaseProvider
    ) {
        super(dbProvider);
    }

    /**
     * Finds an active order by its human-readable order number.
     *
     * @param orderNumber - e.g. `'ORD-20240115-00042'`
     * @returns The order, or `null` if not found or soft-deleted.
     */
    async findByOrderNumber(orderNumber: string): Promise<Order | null> {
        const row = await this.query()
            .where({ order_number: orderNumber })
            .first();
        return row ?? null;
    }

    /**
     * Returns all active orders for a user, newest first.
     *
     * @remarks
     * Uses index `idx_orders_user_created` (user_id, created_at DESC)
     * so the query is O(log n) even on large tables.
     *
     * @param userId - The user whose order history to fetch.
     */
    async findByUserId(userId: string): Promise<Order[]> {
        return this.query()
            .where({ user_id: userId })
            .orderBy("created_at", "desc");
    }

    /**
     * Inserts a new order row within an existing transaction.
     *
     * @remarks
     * `order_number` is generated by the `trigger_generate_order_number`
     * DB trigger  do not include it in `data`.  `status` defaults to
     * `'pending'` via the DB column default.
     *
     * @param data - Partial order fields (`user_id`, `total_amount`, `notes`).
     * @param trx  - The active transaction  always required for writes.
     * @returns The inserted order row including trigger-generated `order_number`.
     */
    async create(data: Partial<Order>, trx: Knex.Transaction): Promise<Order> {
        const [row] = await trx(this.table).insert(data).returning("*");
        return row;
    }

    /**
     * Updates the status of an order.
     *
     * @param id     - Primary key of the order.
     * @param status - The new lifecycle status.
     * @param trx    - Optional transaction client.
     * @returns The updated order, or `null` if not found.
     */
    async updateStatus(
        id: string,
        status: OrderStatus,
        trx?: Knex.Transaction,
    ): Promise<Order | null> {
        const qb = trx ? trx(this.table) : this.db(this.table);
        const [row] = await qb
            .where({ id })
            .update({ status, updated_at: this.db.fn.now() })
            .returning("*");
        return row ?? null;
    }
}
