/**
 * @module orders/types
 * @description Domain types for the orders module.
 *
 * `OrderStatus` follows the order lifecycle:
 *   pending -> confirmed -> processing -> completed
 *                  |
 *                   ------> cancelled / refunded
 */
import { CreateOrderRequestItem, OrderItem } from "modules/order-items/types.js";

/**
 * All possible lifecycle states of an order.
 * Transitions are enforced at the service layer, not the DB layer.
 */
export type OrderStatus =
    | "pending"
    | "confirmed"
    | "processing"
    | "completed"
    | "cancelled"
    | "refunded";

export interface Order {
    id: string;
    user_id: string;
    order_number: string;    // generated by DB trigger: 'ORD-YYYYMMDD-NNNNN'
    total_amount: string;    // DECIMAL returned as string by the pg driver
    status: OrderStatus;
    notes: string | null;
    created_at: Date;
    updated_at: Date;
    deleted_at: Date | null;
}

// ---------------------------------------------------------------------------
// Input / output shapes for the CreateOrderUseCase
// ---------------------------------------------------------------------------

/** Input received from the HTTP layer to create a new order. */
export interface CreateOrderInput {
    userId: string;
    items: CreateOrderRequestItem[];
    notes?: string;
}

/** Value returned by `CreateOrderUseCase.execute()`. */
export interface CreateOrderResult {
    order: Order;
    items: OrderItem[];
}
