import type { Knex } from "knex";

//  Migration: Create orders table 
// Depends on: users
// order_number is auto-generated via trigger (migration 009).
// total_amount is denormalized - it's the amount charged at time of order.
// Even if product prices change later, this order's total is immutable.

export async function up(knex: Knex): Promise<void> {
    await knex.schema.createTable("orders", (table) => {
        //  Primary Key 
        table.increments("id").primary();

        //  Foreign Key 
        // onDelete RESTRICT: cannot delete a user who has orders.
        // Orders are financial records - must be preserved.
        table
            .integer("user_id")
            .unsigned()
            .notNullable()
            .references("id")
            .inTable("users")
            .onDelete("RESTRICT")
            .onUpdate("CASCADE");

        //  Order Number 
        // Human-readable business identifier - separate from internal PK.
        // Format: ORD-YYYYMMDD-XXXXX (e.g. ORD-20240115-00042)
        // Auto-generated by trigger in migration 009.
        // Unique, not-null - set after insert via trigger.
        // Temporarily nullable to allow trigger to set it post-insert.
        table.string("order_number", 30).unique().nullable();

        //  Financials 
        // Snapshot of the total at time of order.
        // Must equal SUM(quantity * price_at_purchase) in order_items.
        table.decimal("total_amount", 14, 2).notNullable();

        //  Status 
        // State machine: pending -> confirmed -> processing -> completed
        //                   | 
        //                    -> cancelled -> refunded
        table
            .enum("status", [
                "pending",
                "confirmed",
                "processing",
                "completed",
                "cancelled",
                "refunded",
            ])
            .notNullable()
            .defaultTo("pending");

        //  Optional Fields 
        table.text("notes").nullable();

        //  Timestamps 
        table.timestamps(true, true);

        // Soft delete - orders are financial records, never hard deleted.
        table.timestamp("deleted_at").nullable();
    });

    //  CHECK Constraints 
    await knex.raw(`
    ALTER TABLE orders
    ADD CONSTRAINT orders_total_amount_positive
    CHECK (total_amount > 0)
  `);
}

export async function down(knex: Knex): Promise<void> {
    await knex.schema.dropTableIfExists("orders");
}
